// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogPeek: typeof import('./src/components/BlogPeek.vue')['default']
    ContentData: typeof import('./src/components/detail/ContentData.vue')['default']
    ContentInfo: typeof import('./src/components/detail/ContentInfo.vue')['default']
    ContentSidebar: typeof import('./src/components/detail/ContentSidebar.vue')['default']
    DropMenu: typeof import('./src/components/DropMenu.vue')['default']
    FootSection: typeof import('./src/components/detail/FootSection.vue')['default']
    HeadSection: typeof import('./src/components/detail/HeadSection.vue')['default']
    MdiBrightness6: typeof import('~icons/mdi/brightness6')['default']
    MdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    MdiClock: typeof import('~icons/mdi/clock')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiCopyright: typeof import('~icons/mdi/copyright')['default']
    MdiEmail: typeof import('~icons/mdi/email')['default']
    MdiFacebook: typeof import('~icons/mdi/facebook')['default']
    MdiFilter: typeof import('~icons/mdi/filter')['default']
    MdiFormatFont: typeof import('~icons/mdi/format-font')['default']
    MdiFormatQuoteClose: typeof import('~icons/mdi/format-quote-close')['default']
    MdiFormatQuoteOpen: typeof import('~icons/mdi/format-quote-open')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiHashtag: typeof import('~icons/mdi/hashtag')['default']
    MdiHeart: typeof import('~icons/mdi/heart')['default']
    MdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    MdiMenuRight: typeof import('~icons/mdi/menu-right')['default']
    MdiPhone: typeof import('~icons/mdi/phone')['default']
    MdiSearch: typeof import('~icons/mdi/search')['default']
    MdiShareVariant: typeof import('~icons/mdi/share-variant')['default']
    MdiSort: typeof import('~icons/mdi/sort')['default']
    MdiTwitter: typeof import('~icons/mdi/twitter')['default']
    MdiViewCompact: typeof import('~icons/mdi/view-compact')['default']
    MdiViewSequential: typeof import('~icons/mdi/view-sequential')['default']
    MdiWeb: typeof import('~icons/mdi/web')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAppBar: typeof import('./src/components/TheAppBar.vue')['default']
    TheAvatar: typeof import('./src/components/TheAvatar.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}

export {}
