// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogPeek: typeof import('./src/components/BlogPeek.vue')['default']
    MdiBrightness6: typeof import('~icons/mdi/brightness6')['default']
    MdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiFilter: typeof import('~icons/mdi/filter')['default']
    MdiFormatFont: typeof import('~icons/mdi/format-font')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiSearch: typeof import('~icons/mdi/search')['default']
    MdiShareVariant: typeof import('~icons/mdi/share-variant')['default']
    MdiSort: typeof import('~icons/mdi/sort')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAppBar: typeof import('./src/components/TheAppBar.vue')['default']
  }
}

export {}
