on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check for git
        run: |
          echo The PR was merged
          pwd
          ls -la
          git status
          git diff --name-only
