on:
  push:
    branches:
      - 'master'
  pull_request:

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.x.x

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile


      - name: Markdown lint
        run: pnpm markdown:lint

      - name: EsLint
        run: pnpm lint

      - name: Stylelint
        run: pnpm stylelint


